---
# tasks file for pxc-checker_install

- name: Debian mysql installation
  import_tasks: pxc-checker_debian.yml
  when: ansible_distribution == "Debian"

- name: Ubuntu mysql installation
  import_tasks: pxc-checker_ubuntu.yml
  when: ansible_distribution == "Ubuntu"

